### ISSUE TITLE
`Papa.parse()`: `comments` option breaks for quoted cells

### ISSUE THREAD

**Issue by NamesMT** [mholt/PapaParse#1031]
If we force `quotes`, or the row is automatically quoted, comments doesn't work as expected.

### Example:
Take this value as the first cell data of a row.
```
# Comment lines should have the
first column start with "#" to
avoid parsing error
```
Because of the usage of newline and quotes, the example cell data above is automatically quoted.  
With the config: `comments: "#"`, we would expect this row to be ignored, however, it's still included in the parsed output.

I have tried configuring every possible options and variant of newline and delimeter for both `unparse` (to create a test csvString data) and `parse`, but I've hit a dead end.

**Comment by pokoli** [comment]
Could you please provide a simple sample code to reproduce your issue? 
This way we can include on our test suite

**Comment by janisdd** [comment]
I think this can be closed. The original problem is solved and it is not clear from the description what the problem actually is (and no example).

**Comment by NamesMT** [comment]
Ah sorry I have forgotten about this issue, the problem is not solved, here is a minimal reproducible on Papaparse's demo page:
Image: ![image](https://github.com/user-attachments/assets/52a0f62e-673d-46f5-a741-d32abd281d28)

Data sample:
```csv
A,B
"# This is a comment row, it is ""quoted"""
# Another comment row, its not quoted
"This is a normal row","A value"
```

**Comment by janisdd** [comment]
Everything seems fine here? What do you expect as a result?

When I uncheck ‘Header row’, I don't get any error message.
Row 2 has only 1 cell, as indicated in the error message.

**Comment by NamesMT** [comment]
@janisdd Row 2 should have been a comment and be ignored.

**Comment by janisdd** [comment]
Why do you think that?

I think we can agree that a line that starts with a comment character is a comment line.

Imagine papaparse would do what you are asking. How would someone encode a row that starts with a `#` and contains quotes, but is not supposed to be a comment row?

```
# this is a comment
# what if this should "not" be a comment?
"# probably write it ""this"" way?"
```

These are just my thoughts and my opinion. I think the problem is simple enough to deal with in some form of preprocessing.
(But I'm not a maintainer, so maybe someone will add this option ;)

**Comment by NamesMT** [comment]
If the dataset is expected to have something that starts with `#`, then you should config another character to use as `comment`?,
That's the whole point of the `comment` config, as long as it starts with a specific string, it is ignored.

Quotes are inevitable (and random) in some cases, like you need linebreaks, or you write comma in a cell inside an editor, it'd be automatically quoted, or some data source enforces quotes.
Being able to only config one comment string that could only work for quoted or unquoted, but not both is definitely unintuitive and is an issue.

**Comment by Joelei** [comment]
Here is a sample:
```
,A,B
#,Comment of A "have
multi lines", Comment of B
,Data of A "have
multi lines", Data of B
```
I expect to read correctly a line of ['Data of A', 'Data of B']. But it doen't act like this.

```
,A,B
#,Comment of A, Comment of B
,Data of A "have
multi lines", Data of B
```
This sample can be parsed correctly.

Does that mean parser doesn't support newline in comment lines??

**Comment by janisdd** [comment]
No, it doesn't. See the lines 
https://github.com/mholt/PapaParse/blob/4af6882e0ea91b0baad30345f190b38d50e7535e/papaparse.js#L1643-L1650
If the line starts with a comment char, the "cursor" is placed after the comment (next line).

Same for fast mode (when the data does not contain quotes:
https://github.com/mholt/PapaParse/blob/4af6882e0ea91b0baad30345f190b38d50e7535e/papaparse.js#L1495-L1496

As in all programming languages, commenting out a line means *don't interpret the line, just skip it*. Papaparse chooses to do the same (the only sensible thing to do).

The interpretation of a commented line would therefore defeat the purpose of comments.

**Comment by janisdd** [comment]
I find this a bit funny...

If a comment line were to interpret the data after the comment character, then there is hardly any difference to not using the comment feature and then removing the lines that begin with a comment character.

**Comment by dboskovic** [comment]
This is obviously out of RFC spec BUT I think PapaParse should have a mode where it can failover into a discovery scenario and try to find possible paths forward. I'm flagging this for a possible future gremlin mode feature.
