### ISSUE TITLE
Issues in new version of papaparse

### ISSUE THREAD

**Issue by kroupacz** [mholt/PapaParse#675]
Hello,
after upgrade to paparse 5.0.0, I have a problem with correct delimiter detection and "header": true config. It look like this issue is related to this commit/change: https://github.com/mholt/PapaParse/commit/f6b1b36c3f8faf5ab8e436709925e1563b0f75de

Below I am sending two files where the problem occurs.
- http://drive.google.com/uc?export=download&id=1NjL0RQ64uD6gpaLfrnSryLuLAzeu-Hm9 - invalid delimiter detection

- http://drive.google.com/uc?export=download&id=1ZBSSBIROPt2w1PsqrWmvgImFBCBxzntr - Incorrect parsing with "header": true config

Both of these files are correctly parsed in papaparse version 4.6.1.

Thank you for fixing this issue.
Tomáš

**Comment by georgeslabreche** [comment]
I believe this is the same issue: https://github.com/mholt/PapaParse/issues/685

**Comment by pokoli** [comment]
Could you test this is fixed on current master? #687 may have fixed this.

**Comment by seth-shaw-unlv** [comment]
I don't believe #685 is a duplicate of this issue. I've posted my example on that thread and the current master doesn't resolve the issue.

**Comment by georgeslabreche** [comment]
I do apologize for mistakingly relating the two different issues!

**Comment by martinstreicher** [comment]
I have a perfectly valid CSV file that will not upload properly in Papa 5 with `header: true`. It worked fine previously. However, if I also enable the `Skip empty lines` feature, the file processes just fine. Oddly though, there are no blank lines in the file. Further, the error in parsing always seems to occur on the final line of the file.

**Comment by pokoli** [comment]
@martinstreicher It will be great if you can share the file or add a simple test case to reproduce the issue. Otherwise it is not possible to provide a fix for it.
