### ISSUE TITLE
Parsing issues when using step function 

### ISSUE THREAD

**Issue by ynicolaou** [mholt/PapaParse#697]
I ran into a few different issues around parsing csv files when using headers and step options.

Specifically around parsing empty lines or lines with partial data. For example i would expect papaparse to handle lines like these:

`,,,`
`,a,b`
`\n`

For the `,,,` and `\n` case i'm actually seeing an exception when i try to use the `skipEmptyLines: 'greedy'` option. Probably the same issue as this https://github.com/mholt/PapaParse/issues/672

Below are some test cases that break:

```
{
	description: "Parsing with skipEmptyLines set to 'greedy' with step",
	notes: "Must parse correctly without lines with no content",
	input: 'a,b\n\n,\nc,d\n , \n""," "\n	,	\n,,,,\n',
	config: { skipEmptyLines: 'greedy', step: function() { return null; } },
	expected: {
		data: [['a', 'b'], ['c', 'd']],
		errors: []
	}
}
```

```
{
	description: "Data is correctly parsed with steps and header when starting with empty value",
	expected: [{"A": "", "b": "E", "c": "f"}],
	run: function(callback) {
		var data = [];
		Papa.parse('A,b,c\n,E,f', {
			header: true,
			step: function(results) {
				data.push(results.data);
			},
			complete: function() {
				callback(data);
			}
		});
	}
}
```

**Comment by mcrodrig** [comment]
I just run yesterday into this issue as well. I can provide test data if needed.

**Comment by pokoli** [comment]
@mcrodrig this should be fixed in 5.0.2

If you are using the step function this should be managed on #697

**Comment by mcrodrig** [comment]
I'm using 5.0.2 with step function, and it is still not working.

With the attached file, the step function is not even invoked. With a bigger file, I got errors as well as shown in the png attached.

![Screenshot 2019-09-17 at 09 30 23](https://user-images.githubusercontent.com/26752359/65020620-d0b83680-d92d-11e9-9443-db40ea3876d1.png)

[events few lines.csv.zip](https://github.com/mholt/PapaParse/files/3619815/events.few.lines.csv.zip)
