### ISSUE TITLE
CSV parsing is broken in 5.4.1

### ISSUE THREAD

**Issue by rpr-ableton** [mholt/PapaParse#998]
Hi everyone,

First of all, big thanks for this great library that's been a big help in my work :raised_hands: 

I noticed when going from 5.3.2 to 5.4.1 that some CSV files can't be parsed successfully anymore. I'll attach below a small CSV, a nodejs script to reproduce the issue as well as the output.

`example.csv`:
```csv
colName_2,colName_3,another_col,entity,some_bool,period,date,value_eur
"foo, bar","foo, bar",foo_bar_baz_V1,bar baz,0,2022_02,02/01/22,1234.45678
"foo, bar","foo, bar",foo_bar_baz_V1,bar baz,0,2022_03,03/01/22,1234.45678
"foo, bar","foo, bar",foo_bar_baz_V2,bar baz,0,2022_11,11/01/22,-12345.67891
"foo, bar","foo, bar",foo_bar_baz_V2,bar baz,0,2022_12,12/01/22,-12345.67891
```

`script.js`:
```javascript
const papa = require('papaparse');
const fs = require('fs');

const readStream = fs.createReadStream(`${ __dirname }/example.csv`);
return papa.parse(readStream, {
    step: (res, parser) => {
        parser.pause();
        Object.keys(res.data).
            sort().
            forEach((key) => {
                console.log(res.data[key]);
            });
        return parser.resume();
    }, // step
    header: true,
    error: (err) => {
        return console.error(err);
    }, // error
    complete: () => {
        console.log('finished');
    }, // complete
}); // return papa.parse
```

Output with papaparse 5.4.1:
```
$ node script.js 
foo_bar_baz_V1
foo, bar
foo, bar
02/01/22
bar baz
2022_02
0
1234.45678
[ '-12345.67891' ]
foo, bar
foo, bar
foo_1, bar"_1,foo_bar_baz_V1,bar baz,0,2022_03,03/01/22,1234.45678
"foo, bar
2022_11
foo_bar_baz_V2
0
bar baz
11/01/22
foo, bar"_1,foo_bar_baz_V2,bar baz,0,2022_12,12/01/22,-12345.67891


 bar"
finished
```

Let me know if you need any additional information to better capture the issue.

Thanks a bunch.

**Comment by pokoli** [comment]
Hi @rpr-ableton 

Could you please describe which is the issue?

**Comment by rpr-ableton** [comment]
The symptoms are:
- some values from the CSV are parsed as arrays containing a single value
- some values get `_1` appended to them for no apparent reason
- the CSV files is not parsed correctly as you can see in the output where multiple values get concatenated together

Maybe to illustrate the point better, here's the output from the same script but using papaparse 5.3.2 :
```
$ node script.js 
foo_bar_baz_V1
foo, bar
foo, bar
02/01/22
bar baz
2022_02
0
1234.45678
foo_bar_baz_V1
foo, bar
foo, bar
03/01/22
bar baz
2022_03
0
1234.45678
foo_bar_baz_V2
foo, bar
foo, bar
11/01/22
bar baz
2022_11
0
-12345.67891
foo_bar_baz_V2
foo, bar
foo, bar
12/01/22
bar baz
2022_12
0
-12345.67891
finished
```

**Comment by pokoli** [comment]
Hi @rpr-ableton, 

We need to isolate the problems with minimal reproducible cases. 
I do not see any reason why a value is converted to an Array. On the other hand the fact of `_1` is appended to the value seems related to the duplicate headers feature and should be fixed with https://github.com/mholt/PapaParse/commit/824bbd9daf17168bddfc5485066771453cab423e

I will need a minimum test scenario in order to be able to fix it. 

BTW: We have included some changes in master version which are not included on latest release. Could you please test with the same version?

**Comment by tjstavenger-pnnl** [comment]
Any update on being able to address this issue? I've recently run into what sounds like a similar problem where a CSV gets parsed with `_1` as the value for some of our values. The same rows with those `_1` values have other columns that are read into the wrong fields of the javascript object.

**Comment by tjstavenger-pnnl** [comment]
Follow-up -- downgrading to papaparse 5.3.2 corrected the problem.

**Comment by raukaute** [comment]
I am experiencing the same issue. Only occurred when using async iterator on stream. Using listeners works without issues.

**Comment by ulo** [comment]
I also got some data consistency issues with parsing csv files in Node using the streaming mode and using "header: true" to get objects. While it works fine with version 5.3.2, starting from 5.4.0 papaparse would change the content of my parsed objects.

As there is no issue using "header: false" I could narrow it down to the following commit https://github.com/mholt/PapaParse/commit/c1cbe16636be146f5f1d321cdd7cbddc9143b045

My guess is, that this code block tries looks for duplicate headers on each new streaming chunk, not just the first line of the first chunk, and thereby modifies not the header but actual data rows...

My solution is to stick with version 5.3.2 for now.

**Comment by pokoli** [comment]
@ulo  What you describe should be fixed with https://github.com/mholt/PapaParse/commit/824bbd9daf17168bddfc5485066771453cab423e which is already released as 5.4.1

**Comment by ulo** [comment]
Thanks for the hint @pokoli !
Indeed, it is apparently not an issue of chunks streaming into Papaparse. I usually create a ReadStream using `fs`, and there the default chunk size of 64KB is much bigger than my actual table, so there will be only 1 chunk streaming into Papaparse.

However, after looking more into Papaparse's source code, the issue is more likely with streaming the parsed objects out of Papaparse. I could figure out that the central parse loop runs fine for the first 16 rows, but then gets paused. It resumes when the destination of my pipeline consumed the first 16 objects, but upon resuming the `baseIndex` is still 0 and therefore the header renaming (which was introduced in version 5.4.0) is happening on the actual data starting from row 17.
The 16 objects correspond to the default `highWaterMark: 16` of object streams in Node. And after the first chunk of 16 objects, it seems that they are processed one by one in the pipeline.



Here is a minimal working example, where I build a pipeline with a first function that generates one big string representing a tsv-table of 20 rows with `id1` and `id2` both set to the row index, and then parsing to objects using papaparse. I consume the pipeline by writing each parsed object to the console:

```typescript
import { Stream } from "stream"
import * as papa from "papaparse"

async function main() {
  const pipeline = Stream.pipeline(
    async function* () {
      yield ["id1\tid2", ...Array.from({ length: 20 }, (v, i) => `${i}\t${i}`)].join("\n")
    },
    papa.parse(papa.NODE_STREAM_INPUT, { delimiter: "\t", newline: "\n", header: true }),
    (err) => err && console.error(err)
  )

  for await (const entry of pipeline) {
    console.log(entry)
  }
}
main()
```

While the example produces the expected output in version 5.3.2, starting from version 5.4.0 the output looks like this:
```typescript
{ id1: '0', id2: '0' }
{ id1: '1', id2: '1' }
{ id1: '2', id2: '2' }
{ id1: '3', id2: '3' }
{ id1: '4', id2: '4' }
{ id1: '5', id2: '5' }
{ id1: '6', id2: '6' }
{ id1: '7', id2: '7' }
{ id1: '8', id2: '8' }
{ id1: '9', id2: '9' }
{ id1: '10', id2: '10' }
{ id1: '11', id2: '11' }
{ id1: '12', id2: '12' }
{ id1: '13', id2: '13' }
{ id1: '14', id2: '14' }
{ id1: '15', id2: '15' }
{ id1: '16', id2: '16_1' }
{ id1: '', id2: '17' }
{ id1: '18', id2: '18_1' }
{ id1: '', id2: '19' }
```

**Comment by jlebras** [comment]
Csv parsing still broken on NodeJS, using v5.4.1 with headers: true.
Wrong number of rows and invalid row objects filled with "_1", "_2", etc.... and concatenated columns that should be distinct values.
The csv file used is valid and parsed correctly using different csv tools.

**Comment by noahw3** [comment]
I'm experiencing exactly what @ulo described above. Streaming on 5.4.1 with `header: true`, the first 16 rows come back fine. The 17th row and beyond are parsed incorrectly.

Converting the stream to a string and parsing that works as expected.

**Comment by basememara** [comment]
I tried the latest `master` branch as of now (https://github.com/mholt/PapaParse/commit/016effe152b218c2545ab70b818f75758cad2e3c) and issue still persists, had to revert back to `5.3.2` :(

**Comment by andynsd** [comment]
Hello - Are there any plans to fix this?

**Comment by codenamezjames** [comment]
I am experiencing this issue too. i had to use another lib for now. Hopefully this can get fixed 🤞

**Comment by ianengelbrecht** [comment]
Having the same issue. step works fine if I don't pause the parser, but rows are not parsed properly with parser.pause(). 

Run the code below with parser.pause and parser.resume commented out, and not commented out, to compare the output. 

```
import fs from 'fs';
import Papa from 'papaparse';

const fileName = String.raw`Theraphosidae 20241116.csv`

const fileStream = fs.createReadStream(fileName);
Papa.parse(fileStream, {
  header: true, // Convert rows to objects using the first row as header
  step: (results, parser) => {
    parser.pause()
    const row = results.data
    console.log(row.vmNumber)
    parser.resume()
  },
  complete: () => {
    console.log('all done')
  },
  error: (error) => reject(error),
});
```
[Theraphosidae 20241116.csv](https://github.com/user-attachments/files/17789873/Theraphosidae.20241116.csv)

**Comment by davidsky** [comment]
Streaming on 5.5.1 with header: true. Getting the same wrong values _1 ... _N.

**Comment by pokoli** [comment]
> Streaming on 5.5.1 with header: true. Getting the same wrong values _1 ... _N.

This is because you have duplicated Headers. Is a new feature introduced in the newer version.

**Comment by gburtini** [comment]
I can repro. this on a very simple implementation.

Emit a dataset like this with from a stream.

```
Foo 1,Foo 2
123,124
124,125
125,126
126,127
127,128
128,129
129,130
130,131
131,132
132,133
133,134
134,135
135,136
136,137
137,138
138,139
139,140
137,137
```

Details don't matter, it just needs a unique header and more than 16 rows.

```ts
const fileStream = createReadStream(TEST_LONG_CSV_PATH, {
  encoding: "utf8",
});
const streamingParse = csvParser.parse(NODE_STREAM_INPUT, {
    header: true,
});
fileStream.pipe(streamingParse);
```

Then consume the stream...

```ts
for await (const record of streamingParse) {
   console.log(record);
}
```

Or

```ts
streamingParse.on("data", (record: Record<string, string>) => {
  console.log("Parsed record:", record);
})
```

At row 16 or 17, you'll get a warning on stderr that says "Duplicate headers found and renamed." indicating it has seemingly forgotten the headers it parsed at the beginning of the stream.

**Comment by rgigger** [comment]
I have taken some time to dive into the codebase and see if I can figure out what is going on here.

In commit `c1cbe16` some code was added to rename headers if there are duplicates. Basically if a line has the same value twice then it adds a `_<${number}>` to the end, where `number` starts off as 1 and increments for each duplicate of that string. That makes a lot of sense for the headers. The problem is that that code run on all lines.

In commit `824bbd9` the author then updated the conditional for when to run the header de-duplication code from `if (config.header)` to `if (config.header && !baseIndex)`. Commit message is "Only test duplicate headers on first row". The problem with this is that if you are pausing the parser on each row to process it asynchronously and then running once it's processed then `baseIndex` is always `0`. Right before `baseIndex` is modified to have a non-zero value there is this code.

```javascript
if (this._handle.paused() || this._handle.aborted()) {
	this._halted = true;
	return;
}
```

The code I am using is basically this but here I'm simply logging out the value of `row.data`.

```javascript
Papa.parse(stream, {
	download: true,
	header: true,
	step: (row, parser) => {
		parser.pause();
		const rowData = row.data;
		(() => {
			console.log({rowData});
			parser.resume();
		})();
	}
});
```

`this._handle.paused()` is then true on every single iteration. So either this is the wrong way to use `papaparse` or there is a bug and the author simply did not test his header de-duplication code with a use case where parsing is paused while each line is processed. Either way it could be great to get word from the author on which one it is.

**Comment by jbool24** [comment]
> > Streaming on 5.5.1 with header: true. Getting the same wrong values _1 ... _N.
> 
> This is because you have duplicated Headers. Is a new feature introduced in the newer version.

I'm not sure this "feature" makes sense to handle. This should be considered as a user error with bad input - "duplicate header names", rather than try to fix this in flow. Can you provide a good case where this would not be user input error and valuable to handle such cases?

**Comment by rgigger** [comment]
> > > Streaming on 5.5.1 with header: true. Getting the same wrong values _1 ... _N.
> > 
> > 
> > This is because you have duplicated Headers. Is a new feature introduced in the newer version.
> 
> I'm not sure this "feature" makes sense to handle. This should be considered as a user error with bad input - "duplicate header names", rather than try to fix this in flow. Can you provide a good case where this would not be user input error and valuable to handle such cases?

I think it's fine as a feature but it should probably be an option, rather than automatically being in effect every time you use `header: true`. But more importantly it just needs to be implemented correctly. There have been a few attempts to correctly determine when it's dealing with the header line vs a data line, and I'm guessing they are correct in a number of cases, for example if you don't pause the parser after each line I think it still works correctly, but it is still trying to apply the de-dup logic to non-header lines, thus breaking its primary use case for many people.

**Comment by jbool24** [comment]
@rgigger I mostly agree on the second half, but I'm still perplexed where there is a good use-case to making duplicate headers be allowed. No other csv parser I've ever used allowed this and treats this as input error. If you think about it being a feature, then what you are allowing is unhandled user input. And we already know historically this is bad new (especially in web environments)

Yes this logic should be "correct", but I stand firm that duplicate headers is a hard error, not something to silently fix. The end users should handle this directly if they want duplicate named headers with ordinal indexes. It only complicates the logic for streams as you've suggested when "pause" and "resume" are applied. We may be at some non-determinate position in the stream at that time and potentially in between chunks.

**Comment by rgigger** [comment]
@jbool24 Yeah I don't have a use for it and would in general not want to use it. I would not be sad if it was removed. But I don't know anything about whatever use cases resulted it in being added so I'm trying to be open minded about it. I wouldn't be sad if it was just ripped out. But if it is to stay in I think it should be an option that defaults to 'off'.

**Comment by magnusjtvisma** [comment]
One use-case for duplicated headers is to mark columns as not relevant. I use a header "notused" for this. In my case I have to deal with a mix of files with/without header, and some formats that were made decades ago with columns I don't care about. It simplifies things a lot to just insert dummy headers with "notused" for the columns I don't care about.

**Comment by LajnaLegenden** [comment]
What is the status of this? I am getting the same error on 5.5.3 and getting the same error. A config option to disable this would be amazing
